<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>JavMetaLite</AssemblyName>
    <RootNamespace>JavMetaLite.App</RootNamespace>
    <Version>1.1.1</Version>
    <FileVersion>1.1.1.0</FileVersion>
    <InformationalVersion>1.1.1</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
    <Authors>Noredge</Authors>
    <Company>Noredge</Company>
    <Copyright>Copyright © 2026 Noredge</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <ApplicationIcon>Resources\Brand\JavMetaLite.ico</ApplicationIcon>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JavMetaLite.Core\JavMetaLite.Core.csproj" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4078.44" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Brand\JavMetaLite.ico" />
    <Resource Include="Resources\Brand\JavMetaLite-64.png" />
  </ItemGroup>
</Project>
